version: "3.9"
services: 
    web:
        build: .
        # command: python app.py
        command: flask run --host=0.0.0.0
        volumes: 
            - .:/code
        ports: 
            - "5000:5000"

        #futuro quando colocar db não esquecer o .env!!!
        #Acessos