version: "3.9"
services: 
    web:
        build: .
        # command: python app.py
        command: gunicorn --bind 0.0.0.0:5000 wsgi:app & gunicorn --limit-request-line 0
        volumes: 
            - .:/code
        ports: 
            - "5000:5000"

        #futuro quando colocar db não esquecer o .env!!!